Stop coverlet clobbering dependencies
coverlet-coverage/coverlet pull request #1156
Opened 2021-04-27 10:43 UTC by ta264

Expose coverlet.core as a package, and pull in dependencies like a normal nuget package.

This stops coverlet clobbering dependencies on publish.

- Fixes #1131 
- Fixes #1106

2021-05-04 19:21 UTC, MarcoRossignoli commented on src/coverlet.core/coverlet.core.csproj
> +  <!-- Nuget package properties https://docs.microsoft.com/en-us/nuget/reference/msbuild-targets -->
At the moment we don't want to expose core lib as package, we discussed this one a lot of times, but for the moment we don't have a stable shape to expose. If we expose core as lib we want to do it in a proper stable way with a public "stable" contract.

2021-05-04 20:09 UTC, MarcoRossignoli requested changes
We're not ready to expose `coverlet.core` as standalone package yet. 
Here you can find some discussion about it, but we didn't reach a mature time/reason to do it yet. 
Maybe we could move on the discussion https://github.com/coverlet-coverage/coverlet/issues/212
Did also some experiment here https://github.com/coverlet-coverage/coverlet/pull/628

2021-05-04 20:31 UTC, ta264 commented
Thanks for the comment. I don't really have a strong view about how this should be fixed but the current behaviour is pretty antisocial and should be changed in my opinion.

2021-05-04 20:43 UTC, MarcoRossignoli commented
I'll keep this open for now as reminder of possibile solution. Thanks for the suggestion!

2021-10-29 18:42 UTC, MarcoRossignoli commented
Worked a bit on this one and maybe I found a way to avoid override without expose core https://github.com/coverlet-coverage/coverlet/pull/1243

2021-10-29 18:42 UTC, closed without merging